#ifndef ISMRMRD_VERSION_H
#define ISMRMRD_VERSION_H

#define ISMRMRD_VERSION_MAJOR 1
#define ISMRMRD_VERSION_MINOR 4
#define ISMRMRD_VERSION_PATCH 0
#define ISMRMRD_XMLHDR_VERSION 4
#define ISMRMRD_GIT_SHA1_HASH "7229d73e4aaa07cba62b2feac5538d27f35bfef1"
#define ISMRMRD_DATASET_SUPPORT true

#endif /* ISMRMRD_VERSION_H */
