#ifndef ISMRMRD_VERSION_H
#define ISMRMRD_VERSION_H

#define ISMRMRD_VERSION_MAJOR 1
#define ISMRMRD_VERSION_MINOR 4
#define ISMRMRD_VERSION_PATCH 0
#define ISMRMRD_XMLHDR_VERSION 4
#define ISMRMRD_GIT_SHA1_HASH "f78ac419a725b2f8dbae17bb6ecb399612bb9090"
#define ISMRMRD_DATASET_SUPPORT true

#endif /* ISMRMRD_VERSION_H */
